const emptyData = {
  id: {
    fullName: 0,
    phoneNumber: 1,
    email: 2,
    linkedIn: 3,
    github: 4,
    languages: 5,
    frameworks: 6,
    devTools: 7,
    libraries: 8,
    linkedInUrl: 9,
    githubUrl: 10,
  },
  school: [],
  experience: [],
  project: [],
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
};

const sampleData = {
  id: {
    fullName: 0,
    phoneNumber: 1,
    email: 2,
    linkedIn: 3,
    github: 4,
    languages: 5,
    frameworks: 6,
    devTools: 7,
    libraries: 8,
    linkedInUrl: 9,
    githubUrl: 10,
  },
  school: [11],
  experience: [12, 14],
  project: [13, 15],
  0: "John Doe",
  1: "123-456-7891",
  2: "johndoe@gmail.com",
  3: "linkedin.com/johndoe",
  4: "github.com/johndoe",
  5: "Javascript, Python, Java, C++, SQL",
  6: "React.js, Next.js, Flutter",
  7: "Git, GitHub, Jira, Postman",
  8: "numpy, pandas, scikit-learn",
  9: "https://www.linkedin.com/",
  10: "https://github.com/",
  11: {
    schoolName: "University of XYZ",
    location: "City, State",
    major: "Bachelors of Science in Computer Science",
    startDate: "August 2020",
    endDate: "May 2024",
  },
  12: {
    positionName: "Software Engineer Intern",
    startDate: "May 2023",
    endDate: "August 2023",
    organization: "ABC Tech Company",
    location: "City, State",
    description: [1, 2, 3, 4],
    1: "Developed a web application using React.js and MongoDB to streamline the company's internal processes",
    2: "Participated in daily scrum meetings, code reviews, and sprint planning sessions",
    3: "Collaborated with cross-functional teams to identify and resolve technical issues",
    4: "Implemented unit and integration tests to ensure code quality and reliability",
    visibility1: "hidden",
    visibility2: "hidden",
    visibility3: "hidden",
    visibility4: "hidden",
  },
  14: {
    positionName: "Mobile App Developer Intern",
    startDate: "May 2022",
    endDate: "August 2022",
    organization: "XYZ Solutions",
    location: "City, State",
    description: [1, 2, 3, 4],
    1: "Designed and developed a mobile app for iOS and Android platforms using Flutter",
    2: "Integrated the app with RESTful APIs to retrieve and display data",
    3: "Performed user experience testing and implemented feedback to improve the app's usability",
    4: "Documented the development process and shared learnings with the team",
    visibility1: "hidden",
    visibility2: "hidden",
    visibility3: "hidden",
    visibility4: "hidden",
  },
  13: {
    projectName: "Recommendation System",
    tools: "Python, scikit-learn",
    startDate: "August 2023",
    endDate: "August 2023",
    description: [1, 2, 3],
    1: "Made a content-based recommendation system using Python and scikit-learn to suggest relevant products",
    2: "Implemented data preprocessing, feature engineering, and model training techniques",
    3: "Evaluated the system's performance using appropriate metrics and made improvements",
    visibility1: "hidden",
    visibility2: "hidden",
    visibility3: "hidden",
  },
  15: {
    projectName: "Distributed File System",
    tools: "Java",
    startDate: "May 2023",
    endDate: "May 2023",
    description: [1, 2, 3],
    1: "Implemented a distributed file system using Java for fault-tolerant and scalable file storage",
    2: "Created key components such as the namenode, datanode, and client-side communication",
    3: "Tested the system's reliability and performance under various failure scenarios",
    visibility1: "hidden",
    visibility2: "hidden",
    visibility3: "hidden",
  },
};

export { emptyData, sampleData };
