const emptyData = {
  id: {
    fullName: 0,
    phoneNumber: 1,
    email: 2,
    linkedIn: 3,
    github: 4,
    languages: 5,
    frameworks: 6,
    devTools: 7,
    libraries: 8,
    linkedInUrl: 9,
    githubUrl: 10,
  },
  school: [],
  experience: [],
  project: [],
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
};

const sampleData = {
  id: {
    fullName: 0,
    phoneNumber: 1,
    email: 2,
    linkedIn: 3,
    github: 4,
    languages: 5,
    frameworks: 6,
    devTools: 7,
    libraries: 8,
    linkedInUrl: 9,
    githubUrl: 10,
  },
  school: [11],
  experience: [12],
  project: [13],
  0: "John Doe",
  1: "123-456-7891",
  2: "johndoe@gmail.com",
  3: "https://www.linkedin.com/johndoe",
  4: "https://github.com/johndoe",
  5: "Javascript, Python, Java, C++, Go, HTML/CSS",
  6: "Next.js, Angular, Flask",
  7: "ESLint, Jest, Chrome DevTools",
  8: "React, numpy, pandas",
  9: "https://www.linkedin.com/",
  10: "https://github.com/",
  11: {
    schoolName: "Some University",
    location: "Somewhere, TX",
    major: "Bachelors of Science in Computer Science",
    startDate: "August 2020",
    endDate: "May 2024",
  },
  12: {
    positionName: "Software Engineer Intern",
    startDate: "May 2024",
    endDate: "August 2024",
    organization: "John Doe Enterprises",
    location: "Dallas, TX",
    description: [1, 2, 3],
    1: "Developed a custom cli tool for in house operations with Bash",
    2: "Improved data retrieval speeds by 20%",
    3: "Attendly daily standups",
    visibility1: "hidden",
    visibility2: "hidden",
    visibility3: "hidden",
  },
  13: {
    projectName: "CV Builder",
    tools: "React, Javascript, HTML, CSS, Vite",
    startDate: "May 2024",
    endDate: "May 2024",
    description: [1, 2, 3],
    1: "Created a simple application to create custom CV's",
    2: "Used React to construct application and Vite to bundle it",
    3: "Developed a feature to turn CV into PDF for download",
    visibility1: "hidden",
    visibility2: "hidden",
    visibility3: "hidden",
  },
};

export { emptyData, sampleData };
